# Deploying the Applications

In this exercise, we will be deploying all the applications in the project to the cloud.

### Perform the Gradle build

. Make sure you are in the `$COURSE_HOME/cf-spring-trader` directory.

. Kick off the Gradle build
+
----
$ ./gradlew clean assemble
----

### Push the applications to CloudFoundry using the manifest-all.yml file

. Edit the manifest-all.yml to change the `name` field to something unique for each of the applications. Otherwise you will get an error if someone else deploys an app that uses the same hostname. (i.e. quotes-> quotes-initials, accounts -> accounts-initials, portfolio -> portfolio-initials, webtrader -> webtrader-initials). You do *not* need unique names for the services since they exist within easch _space_.
+
----
---
timeout: 180
instances: 1
memory: 512M
env:
    SPRING_PROFILES_DEFAULT: cloud
    JAVA_OPTS: -Djava.security.egd=file:///dev/urandom
applications:
- name: quotes-INSTRUCTOR
  path: springboottrades-quotes/build/libs/quotes-0.2.jar
  services:
      - trader-registry
      - config-server
- name: accounts-INSTRUCTOR
  path: springboottrades-accounts/build/libs/accounts-0.2.jar
  services:
      - trader-db
      - trader-registry
      - config-server
- name: portfolio-INSTRUCTOR
  path: springboottrades-portfolio/build/libs/portfolio-0.2.jar
  services:
      - trader-db
      - trader-registry
      - config-server
- name: webtrader-INSTRUCTOR
  memory: 1G
  path: springboottrades-web/build/libs/web-0.2.jar
  services:
      - trader-registry
      - trader-dashboard
      - config-server
----

. Finally, push the application to Cloud Foundry.
+
----
$ cf push -f manifest-all.yml
----

